// GET all courses
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE = 'GET_COURSE';

// OPTIONS
export const GET_THRESHOLD_CONCEPTS = 'GET_THRESHOLD_CONCEPTS';
export const GET_INFORMATION_LITERACY_OBJECTIVES =
  'GET_INFORMATION_LITERACY_OBJECTIVES';
export const GET_MODULES = 'GET_MODULES';
export const GET_LIBRARIANS = 'GET_LIBRARIANS';
